language: php

php:
  - 5.4

install:
  - composer install

before_script:
  - nohup php -S 0.0.0.0:8888 -ddisplay_errors=0 -t web/ web/dispatch.php >/dev/null 2>&1 &

script: phpunit -c tests/phpunit.xml
